apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-server
  labels:
    app: task-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-server
  template:
    metadata:
      labels:
        app: task-server
    spec:
      containers:
        - name: task-server
          image: lisa0922/msc-procesos-tasks:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: LAUNCHDARKLY_SDK_KEY
              valueFrom:
                secretKeyRef:
                  name: launchdarkly-sdk
                  key: sdk-9c5ff1c2-d81e-4dc5-9245-a89d1d4819f3
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
